# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to Soonie's Homepage
email: soonielane007@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
  We're big boogers forgetting simplest things... which can be important some day.
baseurl: # the subpath of your site, e.g. /blog
url: "http://soondaskeleton.github.io" # the base hostname & protocol for your site
twitter_username: soondaskeleton
github_username: soondaskeleton

# Build settings
markdown: kramdown
